version: 0.2

env:
  secrets-manager:
    SONATYPE_USERNAME: "/publish-to-maven-central/sonatype_credentials:SONATYPE_USERNAME"
    SONATYPE_PASSWORD: "/publish-to-maven-central/sonatype_credentials:SONATYPE_PASSWORD"
    MAVEN_CENTRAL_SIGNING_KEY: "/publish-to-maven-central/maven_central_signing_key"
    MAVEN_CENTRAL_SIGNING_KEY_PASSWORD: "/publish-to-maven-central/maven_central_signing_key_password"

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./gradlew clean build publishToSonatype closeAndReleaseSonatypeStagingRepository
